-- ============================================================
-- SCHEMA DO BANCO DE DADOS SUPABASE (POSTGRESQL) - MSGWHATS
-- Cole este código no "SQL Editor" do seu painel Supabase
-- ============================================================

-- 1. Tabela Mensalistas
CREATE TABLE IF NOT EXISTS public.mensalistas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome TEXT NOT NULL,
    telefone TEXT NOT NULL,
    token TEXT UNIQUE NOT NULL DEFAULT encode(gen_random_bytes(9), 'hex'),
    numero_cartao TEXT,
    tipo_vinculo TEXT DEFAULT 'Lojista / Funcionário',
    nome_loja TEXT,
    status_envio TEXT DEFAULT 'Pendente',
    data_envio TIMESTAMPTZ,
    status_cadastro TEXT DEFAULT 'Pendente',
    data_atualizacao TIMESTAMPTZ,
    observacoes TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Adicionar colunas caso a tabela já tenha sido criada anteriormente
ALTER TABLE public.mensalistas ADD COLUMN IF NOT EXISTS numero_cartao TEXT;
ALTER TABLE public.mensalistas ADD COLUMN IF NOT EXISTS tipo_vinculo TEXT DEFAULT 'Lojista / Funcionário';
ALTER TABLE public.mensalistas ADD COLUMN IF NOT EXISTS nome_loja TEXT;

-- 2. Tabela Veículos (Liberação LPR / Placas)
CREATE TABLE IF NOT EXISTS public.veiculos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mensalista_id BIGINT NOT NULL REFERENCES public.mensalistas(id) ON DELETE CASCADE,
    modelo TEXT NOT NULL,
    ano TEXT NOT NULL,
    cor TEXT NOT NULL,
    placa TEXT NOT NULL,
    criado_em TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Tabela Configurações do Sistema
CREATE TABLE IF NOT EXISTS public.configuracoes (
    chave TEXT PRIMARY KEY,
    valor TEXT NOT NULL
);

-- Inserir Configurações Padrão
INSERT INTO public.configuracoes (chave, valor) VALUES
    ('nome_estacionamento', 'Estacionamento Iguatemi Brasília'),
    ('mensagem_template', 'Olá {nome}, tudo bem? 🚗✨\n\nEstamos migrando nosso sistema de controle para leitura automática de placas (LPR)!\n\nAtualize o número do seu cartão, vínculo (loja ou mensalista externo) e os veículos da sua mensalidade no link seguro abaixo:\n\n👉 {link}\n\nObrigado!'),
    ('intervalo_envio_segundos', '10')
ON CONFLICT (chave) DO NOTHING;

-- Habilitar Row Level Security (RLS) para Acesso Seguro
ALTER TABLE public.mensalistas ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.veiculos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.configuracoes ENABLE ROW LEVEL SECURITY;

-- Políticas de Acesso Público para Leitura/Escrita por Token
CREATE POLICY "Permitir leitura publica de mensalistas" ON public.mensalistas FOR SELECT USING (true);
CREATE POLICY "Permitir atualizacao publica de mensalistas" ON public.mensalistas FOR UPDATE USING (true);
CREATE POLICY "Permitir insercao de mensalistas" ON public.mensalistas FOR INSERT WITH CHECK (true);
CREATE POLICY "Permitir exclusao de mensalistas" ON public.mensalistas FOR DELETE USING (true);

CREATE POLICY "Permitir leitura publica de veiculos" ON public.veiculos FOR SELECT USING (true);
CREATE POLICY "Permitir insercao publica de veiculos" ON public.veiculos FOR INSERT WITH CHECK (true);
CREATE POLICY "Permitir exclusao publica de veiculos" ON public.veiculos FOR DELETE USING (true);

CREATE POLICY "Permitir leitura publica de configuracoes" ON public.configuracoes FOR SELECT USING (true);
CREATE POLICY "Permitir atualizacao publica de configuracoes" ON public.configuracoes FOR UPDATE USING (true);

-- Dados Demonstrativos Iniciais
INSERT INTO public.mensalistas (nome, telefone, token, numero_cartao, tipo_vinculo, nome_loja, status_envio, status_cadastro) VALUES
    ('Carlos Eduardo Silva', '5511999887766', 'demo_token_carlos', '123456', 'Lojista / Funcionário', 'Lojas Renner', 'Enviado', 'Atualizado'),
    ('Mariana Souza Santos', '5511988776655', 'demo_token_mariana', '654321', 'Lojista / Funcionário', 'Zara', 'Pendente', 'Pendente'),
    ('Roberto Almeida Costa', '5511977665544', 'demo_token_roberto', '789012', 'Mensalista Externo', 'Mensalista Externo', 'Pendente', 'Pendente')
ON CONFLICT (token) DO NOTHING;

INSERT INTO public.veiculos (mensalista_id, modelo, ano, cor, placa) 
SELECT id, 'Toyota Corolla', '2022', 'Prata', 'ABC1D23' 
FROM public.mensalistas WHERE token = 'demo_token_carlos'
ON CONFLICT DO NOTHING;
